### ISSUE TITLE
error while deploying

### ISSUE THREAD

**Issue by Lucifer7535** [AnjanaMadu/VoiceChatStreamer#7]
Collecting pytgcalls==3.0.0.dev19
  Downloading pytgcalls-3.0.0.dev19-py3-none-any.whl (50 kB)
ERROR: Could not find a version that satisfies the requirement tgcalls==3.0.0.dev4 (from pytgcalls) (from versions: none)
ERROR: No matching distribution found for tgcalls==3.0.0.dev4

please update the requirements.txt file

**Comment by AnjanaMadu** [comment]
Ok. Ill fix

**Comment by AnjanaMadu** [comment]
Deploy again and say status

**Comment by AnjanaMadu** [comment]
closed due to no responce

**Comment by Lucifer7535** [comment]
sorry for the late response, btw it's working now

**Comment by AnjanaMadu** [comment]
thanks
